language: node_js
node_js:
  - 14

services:
  - docker

script:
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user manhvuduc/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manhvuduc/udagram-api-user:v1
